#peripheral initialization
[package]
authors = ["Aaron Kawahara"]
version = "0.1.0"
edition = "2018"
name = "board"

[lib]
bench = false
doctest = false
test = false

[dependencies]
defmt = "0.2.1"
stm32l4xx-hal = { version = "0.6.0", features = ["stm32l4x5"] }

[features]
stm32l4x5 = []
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []