#peripheral initialization
[package]
authors = ["Aaron Kawahara"]
version = "0.1.0"
name = "board"

[lib]
bench = false
doctest = false
test = false

[dependencies]
stm32l4xx-hal = "0.6.0"
defmt = "0.2.1"

[features]
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []