[package]
edition = "2018"
name = "stm32l4p5-pac"
version = "0.1.0"
authors = ["Aaron Kawahara"]

[dependencies]
bare-metal = "0.2.5"
cortex-m = "0.5.11"
vcell = "0.1.3"

[dependencies.cortex-m-rt]
optional = true
version = "0.6.5"

[features]
rt = ["cortex-m-rt/device"]